# spring-boot-docker/docker-compose.yml
version: "3.7"
services:
  mysql-service:
    image: mysql:latest
    networks:
      - spring-boot-mysql-network
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_ecommerce

  products-service:
    restart: always
    build:
      context: .
      dockerfile: ms-products/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-boot-mysql-network
    depends_on:
      - mysql-service

  orders-service:
    restart: always
    build:
      context: .
      dockerfile: ms-orders/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - spring-boot-mysql-network
    depends_on:
      - mysql-service

  feedbacks-service:
    restart: always
    build:
      context: .
      dockerfile: ms-feedbacks/Dockerfile
    ports:
      - "8100:8100"
    networks:
      - spring-boot-mysql-network
    depends_on:
      - mysql-service

networks:
  spring-boot-mysql-network:
    driver: bridge
