server:
  port: 8080
spring:
  application:
    name: ms-product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_ecommerce?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL57Dialect
    flyway:
      url: jdbc:mysql://localhost:3306/db_ecommerce?useTimezone=true&serverTimezone=UTC
      user: root
      password: root
#  springdoc:
#    show-actuator: true
#    api-docs:
#      path: