openapi: 3.0.1
info:
  title: Product Microservice
  version: v1
  description: Microservice created for the second challenge of the Compass UOL scholarship program.
  termsOfService: http://swagger.io/terms/
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: http://localhost:8080
  description: Generated server url
tags:
  - name: Product
    description: Product management
paths:
  /products:
    post:
      tags:
      - Product
      summary: Persist in db new products.
      operationId: createProduct
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductRequestDto'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProductResponseDto'
components:
  schemas:
    ProductRequestDto:
      type: object
      properties:
        name:
          type: string
        value:
          type: number
          format: double
        description:
          type: string
    ProductResponseDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        value:
          type: number
          format: double
        description:
          type: string
